#pragma once
#pragma pack(push)
#pragma pack(1)

#include "xrMath_comiler_defs.h"
#include "xrMath_common.h"
#include "xrMath_types.h"
#include "xrMath_limits.h"
#include "xrMath_constants.h"
#include "xrMath_bitwise.h"
#include "xrMath_flags.h"
#include "xrMath_random.h"
#include "xrMath_utils.h"
#include "xrMath_trigonometry.h"
#include "xrMath_color.h"
#include "xrMath_vector3.h"
#include "xrMath_vector2.h"
#include "xrMath_vector4.h"
#include "xrMath_matrix4x4.h"
#include "xrMath_matrix3x3.h"
#include "xrMath_quaternion.h"
#include "xrMath_rect.h"
#include "xrMath_box2D.h"
#include "xrMath_box3D.h"
#include "xrMath_obb.h"
#include "xrMath_sphere.h"
#include "xrMath_cylinder.h"
#include "xrMath_plane3D.h"
#include "xrMath_plane2D.h"
#include "xrMath_splines.h"
#include "xrMath_matrix_quat_impl.h"
#include "xrMath_compressed_normal.h"

#pragma pack(pop)
